name: Generate feeds and site

on:
  push:
    branches: [ main ]
  schedule:
    # 毎時実行
    - cron: 0 * * * * 
  workflow_dispatch:

jobs:
  generate-feed:
    name: Generate Feed
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: write # NOTE: peaceiris/actions-gh-pages で gh-pages に push するため、contents は write に

    steps:
      - name: Git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Disable package install scripts
        run: pnpm config set ignore-scripts true

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - uses: flatt-security/setup-takumi-guard-npm@8f53b50568e4466f2d92504f349c05b9ffcb8b59 # v1
        with:
          bot-id: ${{ vars.TAKUMI_GUARD_BOT_ID }}

      - name: Install node packages
        run: pnpm install

      - name: Get date
        id: get-date
        run: |
          echo "date="$(/bin/date -u "+%Y%m%d") >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache feed images
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.4
        with:
          path: .cache
          key: ${{ runner.os }}-feed-images-${{ steps.get-date.outputs.date }}

      - name: Generate feed
        run: pnpm feed-generate

      - name: Generate site
        run: pnpm site-build

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # NOTE: 変更履歴が必要な場合は false に変更
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
